export default {
  RESET_APP_DATA: "RESET_APP_DATA",

  // authendtication api
  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FALIURE: "LOGIN_USER_FALIURE",

  // Time frame data
  GET_TODAY_PLACEMENT_DRIVE_REQUEST: "GET_TODAY_PLACEMENT_DRIVE_REQUEST",
  GET_TODAY_PLACEMENT_DRIVE_SUCCESS: "GET_TODAY_PLACEMENT_DRIVE_SUCCESS",
  GET_TODAY_PLACEMENT_DRIVE_FAILURE: "GET_TODAY_PLACEMENT_DRIVE_FAILURE",

  GET_TODAY_EVENT_REQUEST: "GET_TODAY_EVENT_REQUEST",
  GET_TODAY_EVENT_SUCCESS: "GET_TODAY_EVENT_SUCCESS",
  GET_TODAY_EVENT_FAILURE: "GET_TODAY_EVENT_FAILURE",
};
